# Configuration of app
name: test_app

#options
#url: #url of app
#api: #api of this app

#mock settings for other app (basically used in development environment)
#development:
#  scenario:  #other app's name
#    url:
#    database:
#      adapter: mysql
#      encoding: utf8
#      database: lpr_development
#      host: localhost
#      user: root
#      password: root
#    other app's settings

# columns needed for readonly models in test
#readonly_for_test:
#  study_records:
#    integer: interaction_id, user_id, scenario_id
